#include "buffers.h"
#include "../properties.h"

char WRITE_BUFFER[PAGE_SIZE+1];
char READ_BUFFER[PAGE_SIZE+1];
char TABLE_METADATA_PAGE_BUFFER[PAGE_SIZE+1];
char CURRENT_TABLE_PAGE_BUFFER[PAGE_SIZE+1];